archetypeDir           = "archetypes"
author                 = "tt4"
baseUrl                = "/"
buildDrafts            = false
relativeURLs           = true
canonifyUrls           = true
contentDir             = "content"
description            = "Understand more..."
#languageCode           = "en-us"
layoutDir              = "layouts"
publishDir             = "public"
theme                  = "pixyll"
themesDir              = "themes"
title                  = "IdeaRing"
enableEmoji            = true
DefaultContentLanguage = "en"

[Languages]
[Languages.en]
weight = 1

#[Languages.ru]
#weight = 2

[blackfriday]
angledQuotes = true
hrefTargetBlank = true

[indexes]
  category = "categories"
  tag = "tags"

[params]
  search_engine = true
  #google_analytics_id = ""
  twitter_username = "tigertooth4"
  #disqus_shortname = ""
  paginate = 5
